Add Hestia 1.10.3+ Node.js management

diff --git a/bin/v-add-pm2-app b/bin/v-add-pm2-app
--- a/bin/v-add-pm2-app
+++ b/bin/v-add-pm2-app
@@ -1,63 +1,21 @@
 #!/bin/bash
-# info: add web to PM2
+# info: compatibility wrapper for adding a Node.js app to PM2
 # options: USER DOMAIN ENTRYPOINT
 #
 # example: v-add-pm2-app admin wonderland.com
 #
-# This function adds an installed app to pm2
+# This wrapper keeps older plugin revisions working.
 #----------------------------------------------------------#
 #                Variables & Functions                     #
 #----------------------------------------------------------#
 
-# Argument definition
 user=$1
 domain=$2
 entrypoint=$3
 
-# Includes
-# shellcheck source=/etc/hestiacp/hestia.conf
-source /etc/hestiacp/hestia.conf
-# shellcheck source=/usr/local/hestia/func/main.sh
-source $HESTIA/func/main.sh
-# shellcheck source=/usr/local/hestia/func/domain.sh
-source $HESTIA/func/domain.sh
-# load config file
-source_conf "$HESTIA/conf/hestia.conf"
+if [ "$entrypoint" != 'ecosystem.config.js' ]; then
+	echo 'Error: Invalid Node.js entrypoint'
+	exit 1
+fi
 
-# Additional argument formatting
-format_domain
-
-#----------------------------------------------------------#
-#                    Verifications                         #
-#----------------------------------------------------------#
-
-check_args '3' "$#" 'USER DOMAIN ENTRYPOINT'
-is_format_valid 'user' 'domain'
-is_object_valid 'user' 'USER' "$user"
-is_object_unsuspended 'user' 'USER' "$user"
-is_package_full 'WEB_DOMAINS'
-
-is_dir_symlink "$HOMEDIR/$user/web"
-is_dir_symlink "$HOMEDIR/$user/web/$domain"
-
-is_base_domain_owner "$domain"
-
-# Perform verification if read-only mode is enabled
-check_hestia_demo_mode
-
-#----------------------------------------------------------#
-#                       Action                             #
-#----------------------------------------------------------#
-
-pm2 start $HOMEDIR/$user/web/$domain/private/nodeapp/$entrypoint
-pm2 save
-
-#----------------------------------------------------------#
-#                       Hestia                             #
-#----------------------------------------------------------#
-
-# Logging
-$BIN/v-log-action "$user" "Info" "Web" "Added web to PM2 (Name: $domain)."
-log_event "$OK" "$ARGUMENTS"
-
-exit
+exec /usr/local/hestia/bin/v-add-nodejs-app "$user" "$domain"
